spring:
  rabbitmq:
    host: rabbitmq
    port: 15672
    username: guest
    password: guest
    queue: streaminganalytics.queue
    exchange: streaminganalytics.exchange
    routingkey: streaminganalytics.routingkey